[3;J[H[2J
#############################################################
# One click Install Shadowsocks-Python server               #
# Intro: https://teddysun.com/342.html                      #
# Author: Teddysun <i@teddysun.com>                         #
# Thanks: @clowwindy <https://twitter.com/clowwindy>        #
#############################################################

./shadowsocks.sh: line 58: [: ==: unary operator expected
Please input password for shadowsocks-python:
(Default password: teddysun.com):
---------------------------
password = xiaoke
---------------------------

Please input port for shadowsocks-python [1-65535]:
(Default port: 8989):
---------------------------
port = 666
---------------------------


Press any key to start...or Press Ctrl+C to cancel
Hit:1 http://mirrors.ustc.edu.cn/ubuntu xenial InRelease
Hit:2 http://mirrors.ustc.edu.cn/ubuntu xenial-security InRelease
Hit:3 http://mirrors.ustc.edu.cn/ubuntu xenial-updates InRelease
Hit:4 http://mirrors.ustc.edu.cn/ubuntu xenial-proposed InRelease
Hit:5 http://mirrors.ustc.edu.cn/ubuntu xenial-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
automake is already the newest version (1:1.15-4ubuntu1).
cpio is already the newest version (2.11+dfsg-5ubuntu1).
curl is already the newest version (7.47.0-1ubuntu2).
gcc is already the newest version (4:5.3.1-1ubuntu1).
make is already the newest version (4.1-6).
perl is already the newest version (5.22.1-9).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
python-setuptools is already the newest version (20.7.0-1).
unzip is already the newest version (6.0-20ubuntu1).
wget is already the newest version (1.17.1-1ubuntu1).
swig is already the newest version (3.0.8-0ubuntu3).
python-pip is already the newest version (8.1.1-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 75 not upgraded.
Getting Public IP address, Please wait a moment...
Your main public IP is	[32m123.59.76.229[0m

--2016-06-14 15:26:36--  https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-debian
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.19.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.19.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1525 (1.5K) [text/plain]
Saving to: '/etc/init.d/shadowsocks'

     0K .                                                     100%  124M=0s

2016-06-14 15:26:37 (124 MB/s) - '/etc/init.d/shadowsocks' saved [1525/1525]

./shadowsocks.sh: line 58: [: ==: unary operator expected
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 583, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 583, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 583, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 583, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Shadowsocks install failed! Please visit https://teddysun.com/342.html and contact.
